config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :all_books, only: [:index, :create, :update, :destroy]
    respond_to :html, :js

    def index
        sort = params[:sort] || "id"
        @books = Book.order(sort)
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        @book.save
    end

    def edit
        @book = Book.find(params[:id])
        render 'new'
    end

    def update
        @book = Book.find(params[:id])
        @book.update(book_params)
        render 'create'
    end


    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        render 'create'
    end

private
    def all_books
        @books = Book.all
    end

    def book_params
      params.require(:book).permit(:tomes_count, :author, :title, :genre, :publisher, :year, :price, :name, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
      <tr>
        <td><%= book.id %></td>
        <td><%= book.tomes_count %></td>
        <td><%= book.author %></td>
        <td><%= book.title %></td>
        <td><%= book.genre %></td>
        <td><%= book.publisher %></td>
        <td><%= book.year %></td>
        <td><%= book.price %></td>
        <td><%= book.name %></td>
        <td><%= book.comment %></td>
        <td><%=link_to "Изменить", edit_book_path(book), remote: true%></td>
        <td><%=link_to "Удалить", book_path(book), method: :delete, remote: true%></td>
      </tr>

app/views/books/_form.html.erb
<%= form_for @book, html: {class: "nifty_form"}, remote: true do |f| %>
    <%= label_tag(:tomes_count, "Томов") %>
    <%= f.number_field :tomes_count, in: 1..20, step: 1, required: true, placeholder: "Введите количество томов"%><br>
    <%= label_tag(:author, "Автор") %>
    <%= f.text_field :author, required: true, placeholder: "Введите автора" %><br>
    <%= label_tag(:title, "Название") %>
    <%= f.text_field :title, required: true, placeholder: "Введите название" %><br>
    <%= label_tag(:genre, "Жанр") %>
    <%= f.text_field :genre, required: true, placeholder: "Введите жанр" %><br>
    <%= label_tag(:publisher, "Издательство") %>
    <%= f.text_field :publisher, required: true, placeholder: "Введите издательство" %><br>  
    <%= label_tag(:year, "Год издания") %>
    <%= f.number_field :year, in: 0..9999, step: 1, required: true, placeholder: "Введите год издания" %><br>
    <%= label_tag(:price, "Цена") %>
    <%= f.number_field :price, in: 0.01..99999.99, step: 0.01, required: true, placeholder: "Введите цену" %><br>  
    <%= label_tag(:name, "ФИО взявшего книгу") %>
    <%= f.text_field :name, placeholder: "Укажите кто взял книгу" %><br>
    <%= label_tag(:comment, "Примечания") %>
    <%= f.text_field :comment, placeholder: "Введите примечания" %><br>
    <%= f.submit "Добавить" %>
<% end %>

app/views/books/create.js.erb
$('tbody').html("<%= j (render @books)%>");
$('#window-add').slideUp(350);

app/views/books/index.html.erb
<table>
  <thead>
    <tr>
      <td><%= link_to "Индекс", books_path(sort: "id"), remote: true%></td>
      <td><%= link_to "Томов", books_path(sort: "tomes_count"), remote: true%></td>
      <td><%= link_to "Автор", books_path(sort: "author"), remote: true%></td>
      <td><%= link_to "Название", books_path(sort: "title"), remote: true%></td>
      <td><%= link_to "Жанр", books_path(sort: "genre"), remote: true%></td>
      <td><%= link_to "Издательство", books_path(sort: "publisher"), remote: true%></td>
      <td><%= link_to "Год издания", books_path(sort: "year"), remote: true%></td>
      <td><%= link_to "Цена", books_path(sort: "price"), remote: true%></td>
      <td><%= link_to "ФИО взявшего книгу", books_path(sort: "name"), remote: true%></td>
      <td><%= link_to "Примечания", books_path(sort: "comment"), remote: true%></td>
      <td colspan="2">Управление</td>
    </tr>
  </thead>
  <tbody>
    <%= render @books%>
  </tbody>
</table>

app/views/books/index.js.erb
$('tbody').html("<%= j (render @books)%>");
$('#window-add').slideUp(350);

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/new.js.erb
$('#window-add .content').html("<%= j (render 'form') %>");
$('#window-add').slideDown(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataBase Web App 2.0</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= favicon_link_tag 'favicon.png', rel: 'icon', type: 'image/png' %>
  </head>
  
	<body>

<!-- Рабочий стол с ярлыками -->
		<div id="desktop">
			<div class="desktop__shortcut">
				
				<!-- Этот вариант для тестов, чтобы не нужно было вводить пароль входя в главную форму --> 
				<!-- Этот вариант для тестов, чтобы не нужно было вводить пароль входя в главную форму -->

				<!-- Это итоговый вариант  -->
				<a onclick="windowError()"><%= image_tag "icon-my-computer.ico"%><p>My Computer</p></a>
				<!-- Это итоговый вариант -->
			</div>

			<div class="desktop__shortcut">
				<a onclick="windowError()"><%= image_tag "icon-my-documents.ico"%><p>My Documents</p></a>
			</div>
			
			<div class="desktop__shortcut">
				<a onclick="windowError()"><%= image_tag "icon-my-internet-explorer.ico"%><p>Internet Explorer</p></a>
			</div>

			<div class="desktop__shortcut">
				<a onclick="windowError()"><%= image_tag "icon-my-recycle-bin.ico"%><p>Recycle Bin</p></a>
			</div>

			<div class="desktop__shortcut">
				<a onclick="windowLoginOpen()">
						<%= image_tag "icon-my-database-web-app.png"%>
						<p>DataBase<br>Web App 2.0</p></a>
			</div>
		</div>


	<main>

		


		<!-- Окно: Авторизация -->
		<div id="window-login">
			<header>
				<div class="app-icon-name">
					<div class="app-icon">
					</div>
					<div class="app-name">
						Авторизация
					</div>
				</div>
				<div class="app-button">
					<div class="app-button__close">
						<a onclick="windowLoginClose()">
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</div>
				</div>
			</header>
			<div class="content window-login__content">
					<label><b>Имя пользователя</b></label>
					<input id="login-input" type="text" placeholder="Введите логин" name="uname" onclick="closeError()" required>

					<label><b>Пароль</b></label>
					<input id="password-input" type="password" placeholder="Введите пароль" name="psw" onclick="closeError()" required>

					<button type="submit" onclick="loginform()" >Авторизоваться</button>

					<div id="login-error">
						<p><strong>Данные не верны</strong></p><p>Повторите вход ещё раз</p>
					</div>	
			</div>
		</div>



		<!-- Главное окно программы  -->
		<div id="window-main">
			<header>
				<div class="app-icon-name">
					<div class="app-icon">
						<% image_tag "icon-small.png"%>
					</div>
					<div class="app-name" id="user-type">
						DataBase Web App 2.0
						<span id="admin"><strong>[Администратор]</strong></span>
						<span id="user"><strong>[Пользователь]</strong></span>
					</div>
				</div>
				<div class="app-button">
					<div class="app-button__minimize">
						<a onclick="windowMainMinimize()">
							<i class="fa fa-window-minimize" aria-hidden="true"></i>
						</a>
						
					</div>
					<div class="app-button__maximize" id="max2">
						<a onclick="windowMainMaximizeGo()">
							<i class="fa fa-window-maximize" aria-hidden="true"></i>
						</a>
					</div>
					<div class="app-button__maximize" id="max1">
						<a onclick="windowMainMaximizeOut()">
							<i class="fa fa-window-maximize" aria-hidden="true"></i>
						</a>
					</div>
					<div class="app-button__close">
						<a onclick="windowMainClose()">
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</div>
				</div>
			</header>

			<div class="app-menu">
				<ul class="app-menu__main-menu">
					<li><a>Файл</a>
						<ul class="app-menu__sub-menu">
				            <li>
				            	<a onclick="windowDownloadOpen()">Скачать базу данных</a>
				            </li>
				            <li><a onclick="windowMainClose()">Выход</a>
				            </li>
				        </ul>
					<li>
						<a onclick="windowSearchOpen()">Поиск</a>
		    		</li>
					<li>
						<%= link_to "Добавить запись", new_book_path, remote: true %>
				    </li>
					<li>
						<a>Справка</a>
						<ul class="app-menu__sub-menu">
				           	<li>
				           		<a onclick="windowAboutOpen()">О программе</a>
				           	</li>
				   		</ul>
				    </li>
				</ul>
			</div>
		<div id="window-main__content" class="content">
			<%= yield %>
		</div>
	</div>


    <!-- Окно добавления в базу данных -->
		<div id="window-add">
			<header>
				<div class="app-icon-name">
					<div class="app-icon">
					</div>
					<div class="app-name">
						Добавление и редактирование данных
					</div>
				</div>
				<div class="app-button">
					<div class="app-button__close">
						<a onclick="windowAddClose()">
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</div>
				</div>
			</header>
			<div class="content">
			</div>
		</div>



		<!-- Окно: О программе -->
		<div id="window-about">
			<header>
				<div class="app-icon-name">
					<div class="app-icon">
					</div>
					<div class="app-name">
						О программе
					</div>
				</div>
				<div class="app-button">
					<div class="app-button__close">
						<a onclick="windowAboutClose()">
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</div>
				</div>
			</header>
			<div class="content window-about__content">
				<%= image_tag "icon-big.png"%>
				<h3>База данных<br>«Личная библиотека»</h3>
				<p class="copyright">
					Гормаков Сергей <em>(Frontend)</em><br>
					&<br>
					sssprogramer <em>(Backend)</em>
				</p>
				<p>Тверь<br>2017</p>
			</div>
		</div>


		<!-- Окно: Скачать БД -->
		<div id="window-download">
			<header>
				<div class="app-icon-name">
					<div class="app-icon">
					</div>
					<div class="app-name">
						Скачать базу данных
					</div>
				</div>
				<div class="app-button">
					<div class="app-button__close">
						<a onclick="windowDownloadClose()">
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</div>
				</div>
			</header>
			<div class="content">
				<p>Размер базы данных: <strong>526 Кб</strong></p>
				<button>Скачать</button>
			</div>
		</div>


		<!-- Окно: Поиск -->
		<div id="window-search">
			<header>
				<div class="app-icon-name">
					<div class="app-icon">
					</div>
					<div class="app-name">
						 Поиск по базе данных
					</div>
				</div>
				<div class="app-button">
					<div class="app-button__close">
						<a onclick="windowSearchClose()">
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</div>
				</div>
			</header>
			<div class="content">
				<form>
					<input type="text">
					<button><i class="fa fa-search" aria-hidden="true"></i> Искать</button>
				</form>
			</div>
		</div>


		<!-- Окно: Error 404 -->
		<div id="window-error">
			<header>
				<div class="app-icon-name">
					<div class="app-icon">
					</div>
					<div class="app-name">
						Ошибка 404
					</div>
				</div>
				<div class="app-button">
					<div class="app-button__close">
						<a onclick="windowErrorClose()">
							<i class="fa fa-times" aria-hidden="true"></i>
						</a>
					</div>
				</div>
			</header>
			<div class="content">
				<p><strong>К сожалению эта программа не установлена</strong></p>
				<p>Вы можете запустить программу "DataBase Web App 2.0"<br>используя ярлык на рабочем столе</p>
			</div>
		</div>

		<!-- Свёрнутое окно -->
		<div id="turn">
			<a onclick="turnClose()"><%= image_tag "icon-small.png"%> DataBase Web App</a>
		</div>

	</main>
  </body>
</html>